[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
evm_version = 'paris'
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
verbosity = 3
wrap_comments = true
gas_reports = ["ERC721TL", "ERC1155TL", "Doppelganger", "CollectorsChoice", "OnChainArt", "Shatter", "TLCreator", "TLCreatorContractFactory", "TRACE", "ERC721TLM"]
fs_permissions = [{ access = "read", path = "./"}]

[fuzz]
runs = 1024

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
arb_goerli = "${ARB_GOERLI_RPC_URL}"
base_goerli = "${BASE_GOERLI_RPC_URL}"
mainnet = "${ETH_RPC_URL}"
arb = "${ARB_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY}" }
arb_goerli = { key = "${ARBISCAN_KEY}", url = "https://api-goerli.arbiscan.io/api" }
base_goerli = { key = "${BASESCAN_KEY}", url = "https://api-goerli.basescan.org/api" }
mainnet = { key = "${ETHERSCAN_KEY}"}
arb = { key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api" }
base = { key = "${BASESCAN_KEY}", url = "https://api.basescan.org/api" }