[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
gas_reports = ["*"]
fs_permissions = [{ access = "read", path = "./"}]