[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
evm_version = 'paris'
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
verbosity = 3
wrap_comments = true
gas_reports = ["*"]
fs_permissions = [{ access = "read", path = "./"}]