[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
evm_version = 'paris'
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
verbosity = 3
wrap_comments = true
gas_reports = ["ERC721TL", "ERC1155TL", "Doppelganger", "CollectorsChoice", "OnChainArt", "Shatter", "TLCreator", "TLCreatorContractFactory"]
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
arb_goerli = "${ARB_GOERLI_RPC_URL}"
mainnet = "${ETH_RPC_URL}"
arb = "${ARB_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY}" }
arb_goerli = { key = "${ARBISCAN_KEY}", url = "${ARB_GOERLI_VERIFIER_URL}" }
mainnet = { key = "${ETHERSCAN_KEY}"}
arb = { key = "${ARBISCAN_KEY}", url = "${ARB_VERIFIER_URL}" }