name: Run tests

on:
  # Support calling this workflow from other workflows
  workflow_call:
  push:
    # Run this workflow when pushing any branch other than main.
    branches-ignore: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        run: foundry-rs/foundry-toolchain@v1

      - name: Run unit tests
        run: make quick_test