on:
  push:
    branches-ignore:
      - 'main' # All branches but main
    tags-ignore:
      - '**'  # This ignores all tags

name: Test

jobs:
  check:
    name: Transient Labs Creator Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: make install

      - name: Run unit tests
        run: make test_quick