on: [push]

name: Test

jobs:
  check:
    name: Transient Labs Creator Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        run: foundry-rs/foundry-toolchain@v1

      - name: Run unit tests
        run: make quick_test